dir : 
  train_data_dir : ".\\datasets\\shapenet\\train"
  test_data_dir : ".\\datasets\\shapenet\\test"
  checkpoints_dir : ".\\checkpoints\\model"
  results_dir : ".\\results\\compare"


train:
  batch_size : 32
  lr : 0.001
  epochs : 50
  epochs_decay : 50
  save_epoch_freq : 10
  num_workers : 0

model:
  weight : 50
  weight_La : 2
  dc : 20
  da : 3
  min_angle : 30

test:
  double_check : True
  # double_check : False
  
